apiVersion: v1
kind: Template
labels:
  template: oca-gremlin-server
metadata:
  name: oca-gremlin-server
  annotations:
    description: gremlin server setup that creats janus graph with gremlin service and route for the same
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      type: oca-service
      template: oca-gremlin-server-${CHANNELIZER}
    name: oca-gremlin-${CHANNELIZER}
  spec:
    ports:
    - name: "8182"
      port: 8182
      protocol: TCP
      targetPort: 8182
    selector:
      service: oca-gremlin-${CHANNELIZER}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      type: oca-dc
      template: oca-gremlin-server-${CHANNELIZER}
    name: oca-gremlin-${CHANNELIZER}
  spec:
    selector:
      service: oca-gremlin-${CHANNELIZER}
    template:
      metadata:
        labels:
          service: oca-gremlin-${CHANNELIZER}
      spec:
        containers:
        - env:
          - name: REST
            value: ${REST_VALUE}
          - name: CASSANDRA_SERVICE
            value: ${CASSANDRA_SERVICE}
          - name: JAVA_OPTIONS
            value: ${JAVA_OPTIONS}
          image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}"
          imagePullPolicy: Always
          name: oca-gremlin-image
          ports:
          - containerPort: 8182
            protocol: TCP
          resources:
            requests:
              memory: ${MEMORY_REQUEST}
              cpu: ${CPU_REQUEST}
            limits:
              memory: ${MEMORY_LIMIT}
              cpu: ${CPU_LIMIT}
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 30
            failureThreshold: 3
            successThreshold: 1
            tcpSocket:
              port: 8182
          readinessProbe:
            tcpSocket:
              port: 8182
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 30
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange
    replicas: ${{REPLICAS}}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: gremlin-api
    labels:
      type: oca-route
      template: oca-gremlin-server
  spec:
    to:
      kind: Service
      name: oca-gremlin-${CHANNELIZER}
      weight: 100
    port:
      targetPort: '8182'

parameters:
- description: MEMORY_LIMIT
  name: MEMORY_LIMIT
  required: true
  value: "2048Mi"
- description: MEMORY_REQUEST
  name: MEMORY_REQUEST
  required: true
  value: "1280Mi"
- description: CPU_LIMIT
  name: CPU_LIMIT
  required: true
  value: "1000m"
- description: CPU_REQUEST
  name: CPU_REQUEST
  required: true
  value: "300m"
  # TODO - Right now using docker.io for image registry, once CI/CD setup complete then we can move this to quay/internal registry
- description: Docker registry where the image is
  displayName: Docker registry
  required: true
  name: DOCKER_REGISTRY
  value: "docker.io"
- description: Docker image to use
  displayName: Docker image
  required: true
  name: DOCKER_IMAGE
  value: "rajusem/gremlin-http"
- description: Image tag
  displayName: Image tag
  required: true
  name: IMAGE_TAG
  value: "cassandra"
- description: Number of deployment replicas
  displayName: Number of deployment replicas
  required: true
  name: REPLICAS
  value: "1"
- description: Name of the channelizer being used. Setting this will not change the channelizer, this will merely influence the names of OpenShift objects being created. To change the channelizer, see REST_VALUE.
  name: CHANNELIZER
  required: true
  value: http
- description: Change the channelizer being used to deploy the gremlin server. Set this to "1" for HTTP channelizer, and "0" for WebSocket channelizer. Defaults to "0" i.e. WebSocket.
  name: REST_VALUE
  required: true
  value: "1"
- description: Cassandra service name with 9042 port expose to talk to cassandra cql. 
  name: CASSANDRA_SERVICE
  required: true
  value: "rook-cassandra-client"
- description: JVM Options
  name: JAVA_OPTIONS
  required: false
  value: ""